# use_frameworks!

platform :ios, '8.0'

target 'LWLogger_Example' do
  pod 'LWLogger', :path => '../'

  pod 'CocoaLumberjack', '~>3.6.0'
  pod 'SSZipArchive'
  pod 'skpsmtpmessage'

  # pod 'skpsmtpmessage'

  # target 'LWLogger_Tests' do
  #   inherit! :search_paths
  # end
end
